import os
import io
import base64
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import folium

from flask import (
    Flask,
    render_template,
    request,
    send_file,
    flash,
    redirect,
    jsonify
)

from sklearn.linear_model import LinearRegression
from dotenv import load_dotenv
from reportlab.pdfgen import canvas

from datetime import datetime
import google.generativeai as genai

load_dotenv()

genai.configure(
    api_key=os.getenv("GEMINI_API_KEY")
)

model = genai.GenerativeModel(
    "gemini-2.0-flash"
)

app = Flask(__name__)

app.secret_key = "climate_secret_key"

UPLOAD_FOLDER = "datasets"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)

app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER

@app.route("/upload-dataset", methods=["POST"])
def upload_dataset():

    file = request.files.get("dataset")

    if file and file.filename != "":

        filepath = os.path.join(
            app.config["UPLOAD_FOLDER"],
            file.filename
        )

        file.save(filepath)

        flash(
            "Dataset Uploaded Successfully!",
            "success"
        )

    else:

        flash(
            "Please Select a Dataset!",
            "danger"
        )

    return redirect("/admin")

@app.route("/refresh-data")
def refresh_data():

    flash(
        "Dataset Refreshed Successfully!",
        "info"
    )

    return redirect("/admin")

@app.route("/export-data")
def export_data():

    filepath = "datasets/GlobalLandTemperaturesByCity.csv"

    if os.path.exists(filepath):

        return send_file(
            filepath,
            as_attachment=True
        )

    flash(
        "Dataset file not found!",
        "danger"
    )

    return redirect("/admin")


@app.route("/")
def home():
    return render_template("home.html")

@app.route('/chatbot', methods=['POST'])
def chatbot():

    question = request.form['question'].lower()

    responses = {

    "climate change":
    "Climate change is the long-term alteration of temperature and weather patterns caused mainly by human activities.",

    "global warming":
    "Global warming is the increase in Earth's average temperature due to greenhouse gases.",

    "co2":
    "CO₂ emissions from industries, vehicles, and power plants contribute significantly to climate change.",

    "renewable energy":
    "Renewable energy includes solar, wind, hydroelectric, and geothermal energy sources.",

    "risk":
    "Climate risk in India is currently moderate, with some regions facing high temperature stress.",

    "temperature":
    "Rising global temperatures are one of the major indicators of climate change.",

    "greenhouse gases":
    "Greenhouse gases such as CO₂ and methane trap heat in Earth's atmosphere.",

    "methane":
    "Methane is a powerful greenhouse gas released from agriculture, landfills, and fossil fuels.",

    "sea level":
    "Sea levels are rising due to melting glaciers and thermal expansion of oceans.",

    "deforestation":
    "Deforestation increases climate change by reducing the number of trees that absorb CO₂.",

    "solar energy":
    "Solar energy converts sunlight into electricity and helps reduce carbon emissions.",

    "wind energy":
    "Wind energy uses turbines to generate clean electricity without producing greenhouse gases.",

    "air pollution":
    "Air pollution is caused by harmful gases and particles released into the atmosphere.",

    "carbon footprint":
    "A carbon footprint measures the total greenhouse gases generated by human activities.",

    "sustainable development":
    "Sustainable development meets present needs without compromising future generations.",

    "paris agreement":
    "The Paris Agreement is a global treaty aimed at limiting global warming.",

    "india climate":
    "India faces challenges such as heatwaves, floods, droughts, and rising temperatures.",

    "flood":
    "Climate change can increase the frequency and intensity of floods.",

    "drought":
    "Higher temperatures and changing rainfall patterns can lead to drought conditions.",

    "heatwave":
    "Heatwaves are prolonged periods of extremely high temperatures.",

    "glacier":
    "Glaciers are melting rapidly due to rising global temperatures.",

    "ozone":
    "The ozone layer protects Earth from harmful ultraviolet radiation.",

    "recycling":
    "Recycling helps reduce waste and lowers environmental pollution.",

    "electric vehicle":
    "Electric vehicles reduce dependence on fossil fuels and lower emissions.",

    "tree plantation":
    "Planting trees helps absorb CO₂ and improves air quality.",

    "net zero":
    "Net zero means balancing greenhouse gas emissions with removal efforts.",

    "earth":
    "Earth's average temperature has increased significantly since the Industrial Revolution.",

    "climate solution":
    "Climate solutions include renewable energy, afforestation, and sustainable transportation.",

    "prediction":
    "Climate prediction uses historical climate data and machine learning models.",

    "ai":
    "Artificial Intelligence helps analyze climate trends and predict future risks.",

    "india": "India faces climate challenges such as heatwaves, floods, droughts, and rising temperatures.",

"flood": "Floods can become more frequent and severe due to changing rainfall patterns caused by climate change.",

"drought": "Droughts occur when regions receive significantly less rainfall than normal for extended periods.",

"tree": "Trees absorb CO₂ from the atmosphere and help reduce global warming.",

"pollution": "Pollution contaminates air, water, and land, affecting human health and the environment.",

"greenhouse effect": "The greenhouse effect is the process by which gases trap heat in Earth's atmosphere.",

"recycling": "Recycling reduces waste, conserves resources, and lowers environmental pollution.",

"electric vehicle": "Electric vehicles use electricity instead of fossil fuels and help reduce emissions.",

"ozone layer": "The ozone layer protects Earth from harmful ultraviolet rays from the Sun."
        }

    answer = "Sorry, I can answer only climate-related questions."

    for key in responses:
        if key in question:
            answer = responses[key]
            break

    return jsonify({"answer": answer})

@app.route("/dashboard")
def dashboard():

    # Temperature Data
    city_data = pd.read_csv("datasets/GlobalLandTemperaturesByCity.csv")

    city_data = city_data[city_data["Country"] == "India"]

    city_data["dt"] = pd.to_datetime(city_data["dt"])

    city_data["Year"] = city_data["dt"].dt.year

    total_records = len(city_data)

    avg_temp = round(city_data["AverageTemperature"].mean(),2)

    max_temp = round(city_data["AverageTemperature"].max(),2)

    min_temp = round(city_data["AverageTemperature"].min(),2)

    yearly_temp = city_data.groupby("Year")["AverageTemperature"].mean().reset_index()

    # Temperature Trend Chart
    temp_fig = px.line(
        yearly_temp,
        x="Year",
        y="AverageTemperature",
        title="Annual Average Temperature Trend (India)"
    )

    graph_html = temp_fig.to_html(full_html=False)

    # CO2 Data
    co2 = pd.read_csv("datasets/co2_emission.csv")

    if "Annual CO₂ emissions (tonnes )" in co2.columns:
        co2.rename(
            columns={
                "Annual CO₂ emissions (tonnes )": "CO2_Emissions"
            },
            inplace=True
        )

    co2 = co2[["Year", "CO2_Emissions"]].dropna()

    # CO2 Chart
    co2_fig = px.bar(
        co2.tail(30),
        x="Year",
        y="CO2_Emissions",
        title="CO₂ Emissions by Year"
    )

    co2_graph = co2_fig.to_html(full_html=False)

    # Statistics
    total_records = len(city_data)

    avg_temp = round(
        city_data["AverageTemperature"].mean(),
        2
    )

    merged_data = pd.merge(
    yearly_temp,
    co2,
    on="Year",
    how="inner"
    )

    fig, ax = plt.subplots(figsize=(6,4))

    sns.heatmap(
    merged_data[
        ["Year", "AverageTemperature", "CO2_Emissions"]
    ].corr(),
    annot=True,
    cmap="YlOrRd",
    ax=ax
    )

    img = io.BytesIO()
    plt.savefig(img, format='png', bbox_inches='tight')
    img.seek(0)

    heatmap_url = base64.b64encode(
    img.getvalue()
    ).decode()

    plt.close()

    return render_template(
    "dashboard.html",
    total_records=total_records,
    avg_temp=avg_temp,
    max_temp=max_temp,
    min_temp=min_temp,
    graph_html=graph_html,
    co2_graph=co2_graph,
    heatmap_url=heatmap_url
    )

@app.route("/prediction", methods=["GET", "POST"])
def prediction():

    predicted_temp = None
    risk = None
    forecast_graph = None
    recommendations = []

    if request.method == "POST":

        future_year = int(request.form["year"])
        future_co2 = float(request.form["co2"])

        # Load Temperature Data
        city_data = pd.read_csv(
            "datasets/GlobalLandTemperaturesByCity.csv"
        )

        city_data = city_data[
            city_data["Country"] == "India"
        ]

        city_data["dt"] = pd.to_datetime(
            city_data["dt"]
        )

        city_data["Year"] = city_data["dt"].dt.year

        yearly_temp = city_data.groupby(
            "Year"
        )["AverageTemperature"].mean().reset_index()

        # Load CO2 Data
        co2 = pd.read_csv(
            "datasets/co2_emission.csv"
        )

        if "Annual CO₂ emissions (tonnes )" in co2.columns:
            co2.rename(
                columns={
                    "Annual CO₂ emissions (tonnes )":
                    "CO2_Emissions"
                },
                inplace=True
            )

        co2 = co2[["Year", "CO2_Emissions"]].dropna()

        # Merge datasets
        merged = pd.merge(
            yearly_temp,
            co2,
            on="Year",
            how="inner"
        )

        # Remove NULL values
        valid_data = merged[
            ["Year", "CO2_Emissions", "AverageTemperature"]
        ].dropna()

        # Debugging
        print("\n===== VALID DATA =====")
        print(valid_data.head())

        print("\n===== NULL VALUES =====")
        print(valid_data.isnull().sum())

        X = valid_data[
            ["Year", "CO2_Emissions"]
        ]

        y = valid_data[
            "AverageTemperature"
        ]

        # Train Model
        model = LinearRegression()
        model.fit(X, y)

        # Predict Future Temperature
        prediction_input = pd.DataFrame({
            "Year": [future_year],
            "CO2_Emissions": [future_co2]
        })

        predicted_temp = round(
            model.predict(prediction_input)[0],
            2
        )

        # Climate Risk
        if predicted_temp < 25:

            risk = "Low Risk 🟢"

            recommendations = [
                "Maintain green cover",
                "Promote sustainable development",
                "Monitor climate trends"
            ]

        elif predicted_temp < 30:

            risk = "Moderate Risk 🟡"

            recommendations = [
                "Increase tree plantation",
                "Reduce fossil fuel usage",
                "Promote renewable energy",
                "Improve public transport"
            ]

        else:

            risk = "High Risk 🔴"

            recommendations = [
                "Urgent carbon reduction needed",
                "Large-scale afforestation",
                "Reduce industrial emissions",
                "Implement climate adaptation plans"
            ]

        # Forecast Chart
        forecast_years = []
        forecast_temps = []

        for yr in range(2025, future_year + 1):

            pred_input = pd.DataFrame({
                "Year": [yr],
                "CO2_Emissions": [future_co2]
            })

            temp = round(
                model.predict(pred_input)[0],
                2
            )

            forecast_years.append(yr)
            forecast_temps.append(temp)

        # Create Forecast Graph
        plt.figure(figsize=(8, 4))

        plt.plot(
            forecast_years,
            forecast_temps,
            marker="o"
        )

        plt.title("Future Temperature Forecast")
        plt.xlabel("Year")
        plt.ylabel("Temperature (°C)")
        plt.grid(True)

        img = io.BytesIO()

        plt.savefig(
            img,
            format="png",
            bbox_inches="tight"
        )

        img.seek(0)

        forecast_graph = base64.b64encode(
            img.getvalue()
        ).decode()

        plt.close()

    return render_template(
        "prediction.html",
        predicted_temp=predicted_temp,
        risk=risk,
        forecast_graph=forecast_graph,
        recommendations=recommendations
    )

@app.route("/india-map")
def india_map():

    india = folium.Map(
        location=[22.9734, 78.6569],
        zoom_start=5
    )

    # Delhi
    folium.CircleMarker(
        location=[28.6139, 77.2090],
        radius=15,
        popup="Delhi | High Risk 🔴 | Avg Temp: 29°C",
        color="red",
        fill=True
    ).add_to(india)

    # Mumbai
    folium.CircleMarker(
        location=[19.0760, 72.8777],
        radius=12,
        popup="Mumbai | Moderate Risk 🟠 | Avg Temp: 27°C",
        color="orange",
        fill=True
    ).add_to(india)

    # Chennai
    folium.CircleMarker(
        location=[13.0827, 80.2707],
        radius=12,
        popup="Chennai | Moderate Risk 🟠 | Avg Temp: 28°C",
        color="orange",
        fill=True
    ).add_to(india)

    # Bengaluru
    folium.CircleMarker(
        location=[12.9716, 77.5946],
        radius=10,
        popup="Bengaluru | Low Risk 🟢 | Avg Temp: 24°C",
        color="green",
        fill=True
    ).add_to(india)

    # Kolkata
    folium.CircleMarker(
        location=[22.5726, 88.3639],
        radius=15,
        popup="Kolkata | High Risk 🔴 | Avg Temp: 30°C",
        color="red",
        fill=True
    ).add_to(india)

    map_html = india._repr_html_()

    city_stats = [
        {"city":"Delhi","temp":"29°C","risk":"High 🔴"},
        {"city":"Mumbai","temp":"27°C","risk":"Moderate 🟠"},
        {"city":"Chennai","temp":"28°C","risk":"Moderate 🟠"},
        {"city":"Bengaluru","temp":"24°C","risk":"Low 🟢"},
        {"city":"Kolkata","temp":"30°C","risk":"High 🔴"}
    ]

    return render_template(
        "india_map.html",
        map_html=map_html,
        city_stats=city_stats
    )

@app.route("/reports")
def reports():
    return render_template("reports.html")


@app.route("/admin", methods=["GET", "POST"])
def admin():

    if request.method == "POST":

        username = request.form["username"]
        password = request.form["password"]

        if username == "admin" and password == "admin123":

            city_data = pd.read_csv(
                "datasets/GlobalLandTemperaturesByCity.csv"
            )

            city_data = city_data[
                city_data["Country"] == "India"
            ]

            total_records = len(city_data)

            avg_temp = round(
                city_data["AverageTemperature"].mean(),
                2
            )

            total_cities = city_data["City"].nunique()

            return render_template(
                "admin.html",
                total_records=total_records,
                avg_temp=avg_temp,
                total_cities=total_cities
            )

        return render_template(
            "admin_login.html",
            error="Invalid Username or Password"
        )

    return render_template(
        "admin_login.html",
        error=None
    )

@app.route("/download-report")
def download_report():

    pdf_file = "climate_report.pdf"

    c = canvas.Canvas(pdf_file)

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(120, 800, "Climate Change Analysis Report")

    # Date
    c.setFont("Helvetica", 12)
    c.drawString(
        50,
        760,
        f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}"
    )

    # Project Details
    c.drawString(50, 720, "Country: India")
    c.drawString(50, 700, "Project: Climate Change Analysis & Prioritization")
    c.drawString(50, 680, "Machine Learning Model: Linear Regression")

    # Sample Results
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 630, "Climate Summary")

    c.setFont("Helvetica", 12)
    c.drawString(70, 600, "Average Temperature: 25.8 °C")
    c.drawString(70, 580, "Predicted Temperature (2030): 26.14 °C")
    c.drawString(70, 560, "Climate Risk Level: Moderate Risk")
    c.drawString(70, 540, "CO₂ Emissions Trend: Increasing")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(
        50,
        100,
        "Generated by India Climate Analysis Dashboard"
    )

    c.save()

    return send_file(
        pdf_file,
        as_attachment=True
    )
if __name__ == "__main__":
    app.run(debug=True)